[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[features]
with-serde = ["protobuf/with-serde"]

[dependencies]
protobuf = "~2.2"
futures = "0.1"
grpcio = { path = "../grpc-rs" }
raft = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"